---
name: new_ara_app
description: A new Flutter project.
publish_to: none
version: 1.0.2+102212113
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: "^1.0.2"
  easy_localization: "^3.0.1"
  flutter_svg: "^2.0.0+1"
  flutter_secure_storage: "^7.0.1"
  provider: "^6.0.5"
  http: "^1.1.0"
  webview_flutter: "^4.0.7"
  webview_cookie_manager: "^2.0.6"
  dio: "^5.1.2"
  image_picker: "^1.0.2"
  file_picker: "^5.3.1"
  path: "^1.8.3"
  path_provider: "^2.0.15"
  permission_handler: "^10.2.0"
  url_launcher: "^6.1.12"
  html_editor_enhanced: "^2.5.1"
  uuid: "^3.0.7"
  html: "^0.15.4"
  sanitize_html: "^2.0.0"
  flutter_keyboard_visibility: "^5.4.1"
  mime: "^1.0.4"
  http_parser: "^4.0.2"
  flutter_local_notifications: "^15.1.0+1"
  flutter_quill_extensions: "^0.5.0"
  flutter_quill: "^7.4.7"
  delta_to_html: "^0.2.2"
  html2md: "^1.3.1"
  quill_markdown: "^0.1.0"
  markdown_quill: "^2.0.0"
  markdown: "^7.1.1"
  shared_preferences: "^2.2.2"
  file_icon: "^1.0.0"
  flutter_native_splash: "^2.3.7"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: "^2.0.0"
  flutter_driver:
    sdk: flutter
  test: any
flutter:
  uses-material-design: true
  assets:
  - assets/translations/
  - assets/images/
  - assets/icons/
  fonts:
  - family: NotoSansKR
    fonts:
    - asset: assets/fonts/NotoSansKR-Black.otf
      weight: 900
    - asset: assets/fonts/NotoSansKR-Bold.otf
      weight: 700
    - asset: assets/fonts/NotoSansKR-Medium.otf
      weight: 500
    - asset: assets/fonts/NotoSansKR-Regular.otf
      weight: 400
    - asset: assets/fonts/NotoSansKR-Light.otf
      weight: 300
    - asset: assets/fonts/NotoSansKR-Thin.otf
      weight: 100
