name: Deploy to Play Store, App Store

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - production
          - development

env:
  FLUTTER_VERSION: "3.13"
  JAVA_VERSION: "11"

jobs:
  deploy-android:
    name: Deploy to Play Store
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup Flutter environments for Android (Java, Flutter)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}
      # Setup private credentials
      
      # Setup Fastlane environments for Android (Ruby)
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: Install Fastlane
        run: cd android && bundle install && cd ..
